import type { User, Chore } from '../types';

export const MONTHLY_CAP = 100;

export const SEED_USERS: User[] = [
  { id: 'user-parent', name: 'Parent', role: 'parent', monthly_cap: 0, avatar_color: 'bg-amber-500', avatar_emoji: '👨‍👧' },
  { id: 'user-kid1', name: 'Kid 1', role: 'child', monthly_cap: 100, avatar_color: 'bg-indigo-500', avatar_emoji: '🦁' },
  { id: 'user-kid2', name: 'Kid 2', role: 'child', monthly_cap: 100, avatar_color: 'bg-pink-500', avatar_emoji: '🦊' },
];

export const KID_AVATARS = ['🦁', '🦊', '🐯', '🐸', '🦄', '🐙', '🐻', '🐼', '🦋', '🦕', '🐬', '🦅', '🐉', '🌟', '⚡', '🎮', '⚽', '🎸'];

export const SEED_CHORES: Omit<Chore, 'id' | 'created_at'>[] = [
  // ── DAILY HABITS ──────────────────────────────────
  {
    title: 'Make Bed',
    description: 'Make your bed neatly — pillows straight, blanket smooth',
    assigned_user_id: 'user-kid1',
    frequency: 'daily',
    value: 0.34,
    due_time: '08:00',
    verification_type: 'photo',
    checklist_items: [],
    requires_before_after: false,
    active: true,
    week_days: [],
  },
  {
    title: 'Brush Teeth (Morning)',
    description: 'Brush for at least 2 minutes before school',
    assigned_user_id: 'user-kid1',
    frequency: 'daily',
    value: 0.27,
    due_time: '08:00',
    verification_type: 'photo',
    checklist_items: [],
    requires_before_after: false,
    active: true,
    week_days: [],
  },
  {
    title: 'Shoes Put Away',
    description: 'Shoes in the closet or shoe rack, not the floor',
    assigned_user_id: 'user-kid1',
    frequency: 'daily',
    value: 0.20,
    due_time: '20:00',
    verification_type: 'photo',
    checklist_items: [],
    requires_before_after: false,
    active: true,
    week_days: [],
  },
  {
    title: 'Backpack Hung Up',
    description: 'Backpack on the hook, not on the floor',
    assigned_user_id: 'user-kid1',
    frequency: 'daily',
    value: 0.20,
    due_time: '17:00',
    verification_type: 'photo',
    checklist_items: [],
    requires_before_after: false,
    active: true,
    week_days: [],
  },
  {
    title: 'Brush Teeth (Night)',
    description: 'Brush before bed',
    assigned_user_id: 'user-kid1',
    frequency: 'daily',
    value: 0.27,
    due_time: '21:00',
    verification_type: 'photo',
    checklist_items: [],
    requires_before_after: false,
    active: true,
    week_days: [],
  },
  {
    title: 'Bedroom Surfaces Clean',
    description: 'Desk, nightstand, and dresser cleared and wiped',
    assigned_user_id: 'user-kid1',
    frequency: 'daily',
    value: 0.40,
    due_time: '20:00',
    verification_type: 'photo',
    checklist_items: [],
    requires_before_after: false,
    active: true,
    week_days: [],
  },
  // Kid 2 daily habits
  {
    title: 'Make Bed',
    description: 'Make your bed neatly — pillows straight, blanket smooth',
    assigned_user_id: 'user-kid2',
    frequency: 'daily',
    value: 0.34,
    due_time: '08:00',
    verification_type: 'photo',
    checklist_items: [],
    requires_before_after: false,
    active: true,
    week_days: [],
  },
  {
    title: 'Brush Teeth (Morning)',
    description: 'Brush for at least 2 minutes before school',
    assigned_user_id: 'user-kid2',
    frequency: 'daily',
    value: 0.27,
    due_time: '08:00',
    verification_type: 'photo',
    checklist_items: [],
    requires_before_after: false,
    active: true,
    week_days: [],
  },
  {
    title: 'Shoes Put Away',
    description: 'Shoes in the closet or shoe rack, not the floor',
    assigned_user_id: 'user-kid2',
    frequency: 'daily',
    value: 0.20,
    due_time: '20:00',
    verification_type: 'photo',
    checklist_items: [],
    requires_before_after: false,
    active: true,
    week_days: [],
  },
  {
    title: 'Backpack Hung Up',
    description: 'Backpack on the hook, not on the floor',
    assigned_user_id: 'user-kid2',
    frequency: 'daily',
    value: 0.20,
    due_time: '17:00',
    verification_type: 'photo',
    checklist_items: [],
    requires_before_after: false,
    active: true,
    week_days: [],
  },
  {
    title: 'Brush Teeth (Night)',
    description: 'Brush before bed',
    assigned_user_id: 'user-kid2',
    frequency: 'daily',
    value: 0.27,
    due_time: '21:00',
    verification_type: 'photo',
    checklist_items: [],
    requires_before_after: false,
    active: true,
    week_days: [],
  },
  {
    title: 'Bedroom Surfaces Clean',
    description: 'Desk, nightstand, and dresser cleared and wiped',
    assigned_user_id: 'user-kid2',
    frequency: 'daily',
    value: 0.40,
    due_time: '20:00',
    verification_type: 'photo',
    checklist_items: [],
    requires_before_after: false,
    active: true,
    week_days: [],
  },
  // ── WEEKLY BONUS ──────────────────────────────────
  {
    title: 'Clean a Full Bathroom',
    description: 'Sink, mirror, toilet, floor, and trash — all done',
    assigned_user_id: 'user-kid1',
    frequency: 'weekly',
    value: 3.00,
    due_time: '20:00',
    verification_type: 'both',
    checklist_items: ['Sink scrubbed', 'Mirror cleaned', 'Toilet cleaned', 'Floor mopped/swept', 'Trash emptied'],
    requires_before_after: true,
    active: true,
    week_days: [0, 6],
  },
  {
    title: 'Do Your Own Laundry',
    description: 'Wash, dry, fold, and put away your laundry',
    assigned_user_id: 'user-kid1',
    frequency: 'weekly',
    value: 3.00,
    due_time: '20:00',
    verification_type: 'both',
    checklist_items: ['Clothes washed', 'Clothes dried', 'Folded and put away'],
    requires_before_after: false,
    active: true,
    week_days: [0, 6],
  },
  {
    title: 'Mop the Downstairs Floor',
    description: 'Sweep then mop the entire downstairs floor',
    assigned_user_id: 'user-kid1',
    frequency: 'weekly',
    value: 4.00,
    due_time: '20:00',
    verification_type: 'photo',
    checklist_items: [],
    requires_before_after: true,
    active: true,
    week_days: [0, 6],
  },
  {
    title: 'Mow the Lawn',
    description: 'Mow the front and back yard',
    assigned_user_id: 'user-kid1',
    frequency: 'weekly',
    value: 12.00,
    due_time: '20:00',
    verification_type: 'photo',
    checklist_items: [],
    requires_before_after: true,
    active: true,
    week_days: [6],
  },
  {
    title: 'Clean a Full Bathroom',
    description: 'Sink, mirror, toilet, floor, and trash — all done',
    assigned_user_id: 'user-kid2',
    frequency: 'weekly',
    value: 3.00,
    due_time: '20:00',
    verification_type: 'both',
    checklist_items: ['Sink scrubbed', 'Mirror cleaned', 'Toilet cleaned', 'Floor mopped/swept', 'Trash emptied'],
    requires_before_after: true,
    active: true,
    week_days: [0, 6],
  },
  {
    title: 'Do Your Own Laundry',
    description: 'Wash, dry, fold, and put away your laundry',
    assigned_user_id: 'user-kid2',
    frequency: 'weekly',
    value: 3.00,
    due_time: '20:00',
    verification_type: 'both',
    checklist_items: ['Clothes washed', 'Clothes dried', 'Folded and put away'],
    requires_before_after: false,
    active: true,
    week_days: [0, 6],
  },
  {
    title: 'Mop the Downstairs Floor',
    description: 'Sweep then mop the entire downstairs floor',
    assigned_user_id: 'user-kid2',
    frequency: 'weekly',
    value: 4.00,
    due_time: '20:00',
    verification_type: 'photo',
    checklist_items: [],
    requires_before_after: true,
    active: true,
    week_days: [0, 6],
  },
  {
    title: 'Mow the Lawn',
    description: 'Mow the front and back yard',
    assigned_user_id: 'user-kid2',
    frequency: 'weekly',
    value: 12.00,
    due_time: '20:00',
    verification_type: 'photo',
    checklist_items: [],
    requires_before_after: true,
    active: true,
    week_days: [6],
  },
  // ── ANYTIME BONUS ─────────────────────────────────
  {
    title: 'Unload the Dishwasher',
    description: 'Unload all clean dishes and put them away',
    assigned_user_id: 'user-kid1',
    frequency: 'anytime',
    value: 1.00,
    due_time: '23:59',
    verification_type: 'photo',
    checklist_items: [],
    requires_before_after: true,
    active: true,
    week_days: [],
  },
  {
    title: 'Cook Dinner',
    description: 'Cook a full meal for the family',
    assigned_user_id: 'user-kid1',
    frequency: 'anytime',
    value: 5.00,
    due_time: '23:59',
    verification_type: 'photo',
    checklist_items: [],
    requires_before_after: false,
    active: true,
    week_days: [],
  },
  {
    title: 'Organize a Closet or Drawer',
    description: 'Pick one closet or drawer and fully organize it',
    assigned_user_id: 'user-kid1',
    frequency: 'anytime',
    value: 3.00,
    due_time: '23:59',
    verification_type: 'photo',
    checklist_items: [],
    requires_before_after: true,
    active: true,
    week_days: [],
  },
  {
    title: 'Wash Windows',
    description: 'Wash windows inside and out including sills ($2 per window)',
    assigned_user_id: 'user-kid1',
    frequency: 'anytime',
    value: 2.00,
    due_time: '23:59',
    verification_type: 'photo',
    checklist_items: [],
    requires_before_after: true,
    active: true,
    week_days: [],
  },
  {
    title: 'Take the Dogs Out',
    description: 'Take the dogs outside for a walk or bathroom break',
    assigned_user_id: 'user-kid1',
    frequency: 'anytime',
    value: 0.50,
    due_time: '23:59',
    verification_type: 'photo',
    checklist_items: [],
    requires_before_after: false,
    active: true,
    week_days: [],
  },
  {
    title: 'Unload the Dishwasher',
    description: 'Unload all clean dishes and put them away',
    assigned_user_id: 'user-kid2',
    frequency: 'anytime',
    value: 1.00,
    due_time: '23:59',
    verification_type: 'photo',
    checklist_items: [],
    requires_before_after: true,
    active: true,
    week_days: [],
  },
  {
    title: 'Cook Dinner',
    description: 'Cook a full meal for the family',
    assigned_user_id: 'user-kid2',
    frequency: 'anytime',
    value: 5.00,
    due_time: '23:59',
    verification_type: 'photo',
    checklist_items: [],
    requires_before_after: false,
    active: true,
    week_days: [],
  },
  {
    title: 'Organize a Closet or Drawer',
    description: 'Pick one closet or drawer and fully organize it',
    assigned_user_id: 'user-kid2',
    frequency: 'anytime',
    value: 3.00,
    due_time: '23:59',
    verification_type: 'photo',
    checklist_items: [],
    requires_before_after: true,
    active: true,
    week_days: [],
  },
  {
    title: 'Wash Windows',
    description: 'Wash windows inside and out including sills ($2 per window)',
    assigned_user_id: 'user-kid2',
    frequency: 'anytime',
    value: 2.00,
    due_time: '23:59',
    verification_type: 'photo',
    checklist_items: [],
    requires_before_after: true,
    active: true,
    week_days: [],
  },
  {
    title: 'Take the Dogs Out',
    description: 'Take the dogs outside for a walk or bathroom break',
    assigned_user_id: 'user-kid2',
    frequency: 'anytime',
    value: 0.50,
    due_time: '23:59',
    verification_type: 'photo',
    checklist_items: [],
    requires_before_after: false,
    active: true,
    week_days: [],
  },
];

export const STATUS_LABELS: Record<string, string> = {
  pending: 'Pending',
  submitted: 'Submitted',
  approved: 'Approved',
  rejected: 'Rejected',
  overdue: 'Overdue',
};

export const STATUS_COLORS: Record<string, string> = {
  pending: 'bg-sky-100 text-sky-700',
  submitted: 'bg-yellow-100 text-yellow-700',
  approved: 'bg-emerald-100 text-emerald-700',
  rejected: 'bg-red-100 text-red-700',
  overdue: 'bg-orange-100 text-orange-700',
};

export const VERIFICATION_LABELS: Record<string, string> = {
  photo: 'Photo Required',
  checklist: 'Checklist Required',
  both: 'Photo + Checklist',
  parent_only: 'Parent Inspection',
};
